// Do not edit this file!
// This file was autogenerated by running:
// config_gen.py firebase_config.json
export const config = {
    "apiKey": "AIzaSyCCGclMaIzY0VCCnpOABNQYsdHIGBrgCnA",
    "appId": "1:675834675829:web:6ab1ded70796adcaf42e3c",
    "authDomain": "android-emulator-webrtc-8a806.firebaseapp.com",
    "messagingSenderId": "675834675829",
    "projectId": "android-emulator-webrtc-8a806",
    "storageBucket": "android-emulator-webrtc-8a806.appspot.com"
};