FROM node:20

RUN apt-get update && apt-get install -y adb aapt

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 3000

RUN chmod +x ./install_adb_key.sh

CMD ["./install_adb_key.sh"]
