version: "3.7"
services:
  front-envoy:
    image: emulator_envoy:latest
    build:
      context: .
      dockerfile: envoy.Dockerfile
    networks:
      - envoymesh
    expose:
      - "80"
      - "8001"
    ports:
      - "80:80"
      - "8001:8001"

  emulator:
    image: emulator_emulator:latest
    environment:
      - TURN=printf '{"iceServers":[{"urls":"stun:stun.relay.metered.ca:80"},{"urls":"turn:a.relay.metered.ca:80","username":"26053a6b58a7ac6f6b0b6b9b","credential":"7GoWSUk/SCi0DgMR"},{"urls":"turn:a.relay.metered.ca:80?transport=tcp","username":"26053a6b58a7ac6f6b0b6b9b","credential":"7GoWSUk/SCi0DgMR"},{"urls":"turn:a.relay.metered.ca:443","username":"26053a6b58a7ac6f6b0b6b9b","credential":"7GoWSUk/SCi0DgMR"},{"urls":"turn:a.relay.metered.ca:443?transport=tcp","username":"26053a6b58a7ac6f6b0b6b9b","credential":"7GoWSUk/SCi0DgMR"}]}'
    build:
      context: ../../bld/emulator
      dockerfile: Dockerfile
    networks:
      envoymesh:
        aliases:
          - emulator
    devices: [/dev/kvm]
    shm_size: 128M
    expose:
      - "5555"
      - "8554"
  nginx:
    image: emulator_nginx:latest
    build:
      context: ..
      dockerfile: docker/nginx.Dockerfile
    networks:
      envoymesh:
        aliases:
          - nginx
    expose:
      - "80"
  api:
    build:
      context: ../../backend
    secrets:
      - adbkey
    networks:
      envoymesh:
        aliases:
          - api
    expose:
      - "3000"
    ports:
      - "3000:3000"

networks:
  envoymesh: {}
secrets:
  adbkey:
    file: ~/.android/adbkey
